import { CaretDownIcon as CaretDown, CaretRightIcon as CaretRight, CaretUpIcon as CaretUp, CheckIcon as Check, CubeIcon as Cube, ElevatorIcon as Elevator, PackageIcon as Package, StairsIcon as Stairs } from "@phosphor-icons/react";
import { useState, type ReactNode } from "react";

import type { ScopeReview } from "@/features/workflow/api/workflow-api";

const money = (value: number | null | undefined) => value == null ? "금액 확인 중" : `${new Intl.NumberFormat("ko-KR").format(value)}원`;

export function AgreementOverview({ children, hasIssue = false, onOpenHistory, scope }: { children?: ReactNode; hasIssue?: boolean; onOpenHistory: () => void; scope: ScopeReview }) {
  const [amountOpen, setAmountOpen] = useState(true);
  const [expanded, setExpanded] = useState<Record<"scope" | "origin" | "destination", boolean>>({ scope: false, origin: false, destination: false });
  const toggle = (key: keyof typeof expanded) => setExpanded((current) => ({ ...current, [key]: !current[key] }));
  const pending = scope.collaboration_status === "awaiting_confirmation";
  const originConditions = scope.scope.location_conditions.find((item) => item.kind === "origin");
  const destinationConditions = scope.scope.location_conditions.find((item) => item.kind === "destination");
  return <>
    <div className="-mt-2 mb-1 flex min-h-11 items-center justify-between"><p className="text-ui-data text-ink-600">현재 버전 <strong className="ml-1 text-ink-900">{scope.scope.version_label}</strong></p><button className="flex min-h-11 items-center gap-1 text-ui-data text-primary-700" onClick={onOpenHistory} type="button">변경 이력 {scope.approved_changes.length > 0 ? scope.approved_changes.length : ""} <CaretRight aria-hidden="true" size="var(--icon-xs)" weight="bold" /></button></div>
    {children}
    <section className="ui-card p-3"><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-black">금액 내역</h2><p className="mt-0.5 text-xs text-ink-600">기존 합의 {money(scope.quote?.base_amount_krw)}</p></div><button aria-expanded={amountOpen} aria-label={amountOpen ? "금액 내역 접기" : "금액 내역 펼치기"} className="grid size-11 shrink-0 place-items-center rounded-full hover:bg-surface-muted" onClick={() => setAmountOpen((open) => !open)} type="button">{amountOpen ? <CaretUp aria-hidden="true" size="var(--icon-sm)" /> : <CaretDown aria-hidden="true" size="var(--icon-sm)" />}</button></div>{amountOpen ? <div className="mt-3 divide-y divide-dashed divide-line border-y border-line"><div className="flex items-center justify-between py-3 text-sm"><span>기본 견적</span><strong className="tabular-nums">{money(scope.quote?.base_amount_krw)}</strong></div>{scope.quote?.adjustments.map((item) => <div className="flex items-start justify-between gap-4 py-3 text-sm" key={`${item.label}-${item.amount_krw}`}><span className="min-w-0"><span className="mr-1.5 inline-flex rounded-md border border-warning px-1.5 py-0.5 text-ui-micro font-extrabold text-warning-ink">추가</span>{item.label}</span><strong className="shrink-0 tabular-nums text-warning-ink">{item.amount_krw > 0 ? "+" : ""}{money(item.amount_krw)}</strong></div>)}</div> : null}<div className="mt-3 flex items-end justify-between gap-3"><strong className="text-ui-support">변경 후 금액</strong><strong className="text-ui-section tracking-[var(--tracking-display)] tabular-nums">{money(scope.quote?.total_amount_krw)}</strong></div><button className="mt-2 flex min-h-11 w-full items-center justify-center gap-1 whitespace-nowrap text-ui-data text-ink-600" onClick={() => setAmountOpen((open) => !open)} type="button">내역 {amountOpen ? "접기" : "펼치기"} {amountOpen ? <CaretUp aria-hidden="true" size="var(--icon-xs)" /> : <CaretDown aria-hidden="true" size="var(--icon-xs)" />}</button></section>
    <section className="ui-card p-3"><p className="text-xs text-ink-600">현재 상황</p><h2 className="mt-0.5 text-lg font-black"><span className="text-primary-700">{pending ? "업체 확인 완료" : "공동확인 완료"}</span> · {hasIssue ? "현장 변경 확인" : "작업 범위 확인"}</h2><AgreementProgress pending={pending} /><p className="mt-2 text-xs text-ink-600">{scope.agreement_notice}</p></section>
    <section className="ui-card p-3"><h2 className="text-xs text-ink-600">확인할 작업</h2><ConfirmedRow detail={<ul className="space-y-2">{scope.scope.included_works.map((work) => <li className="flex items-center gap-2" key={work}><Check aria-hidden="true" className="text-success" size="var(--icon-xs)" weight="bold" />{work}</li>)}<li className="flex items-center gap-2"><Package aria-hidden="true" className="text-primary-700" size="var(--icon-xs)" />전체 짐 {scope.scope.item_count}개</li></ul>} expanded={expanded.scope} icon={<Cube aria-hidden="true" size="var(--icon-sm)" weight="duotone" />} label="작업 범위" onToggle={() => toggle("scope")} value={`짐 ${scope.scope.item_count}개 · ${scope.scope.included_works.slice(0, 2).join(" · ")}`} /><ConfirmedRow detail={<ConditionDetails value={originConditions?.conditions} />} expanded={expanded.origin} icon={<Stairs aria-hidden="true" size="var(--icon-sm)" weight="duotone" />} label="출발지 조건" onToggle={() => toggle("origin")} value={conditionSummary(originConditions?.conditions)} /><ConfirmedRow detail={<ConditionDetails value={destinationConditions?.conditions} />} expanded={expanded.destination} icon={<Elevator aria-hidden="true" size="var(--icon-sm)" weight="duotone" />} label="도착지 조건" onToggle={() => toggle("destination")} value={conditionSummary(destinationConditions?.conditions)} /></section>
  </>;
}

const conditionLabels: Record<string, string> = { residence_type: "주거 형태", floor: "층수", elevator: "엘리베이터", stairs: "계단", parking_access: "주차", carry_distance: "운반 거리", access_note: "접근 메모" };
const conditionValue = (value: unknown) => typeof value === "object" && value !== null ? Object.values(value).filter(Boolean).join(" · ") : String(value ?? "확인 필요").replaceAll("_", " ");
const conditionSummary = (conditions: Record<string, unknown> | undefined) => conditions ? [conditions.floor, conditions.elevator, conditions.parking_access].map(conditionValue).filter(Boolean).join(" · ") : "조건 확인 필요";
function ConditionDetails({ value }: { value: Record<string, unknown> | undefined }) {
  if (!value) return <p>등록된 위치 조건이 없습니다.</p>;
  return <dl className="grid grid-cols-[88px_1fr] gap-y-2">{Object.entries(value).map(([key, item]) => <span className="contents" key={key}><dt className="text-ink-600">{conditionLabels[key] ?? key}</dt><dd>{conditionValue(item)}</dd></span>)}</dl>;
}

function AgreementProgress({ pending }: { pending: boolean }) {
  const current = pending ? 3 : 4;
  const steps = ["촬영", "업체 제안", "내 확인", "공동확인"];
  return <ol className="mt-3 grid grid-cols-4">{steps.map((label, index) => { const step = index + 1; const done = step < current; const active = step === current; return <li className="relative text-center" key={label}>{index > 0 ? <span aria-hidden="true" className={`absolute top-3 right-1/2 h-0.5 w-full ${step <= current ? done ? "bg-success" : "bg-primary-600" : "bg-line"}`} /> : null}<span className={`relative z-10 mx-auto grid size-6 place-items-center rounded-full border-2 text-ui-micro font-black ${done ? "border-success bg-success text-white" : active ? "border-primary-600 bg-primary-600 text-white" : "border-line bg-surface-muted text-ink-400"}`}>{done ? <Check aria-hidden="true" size="var(--icon-xs)" weight="bold" /> : step}</span><span className={`mt-1 block text-ui-micro font-bold ${active ? "text-primary-700" : done ? "text-success" : "text-ink-600"}`}>{label}</span></li>; })}</ol>;
}

function ConfirmedRow({ detail, expanded, icon, label, onToggle, value }: { detail: ReactNode; expanded: boolean; icon: ReactNode; label: string; onToggle: () => void; value: string }) {
  return <div className="border-b border-line last:border-b-0"><button aria-expanded={expanded} className="press-static flex min-h-12 w-full items-center gap-2.5 text-left" onClick={onToggle} type="button"><span className="grid size-8 shrink-0 place-items-center rounded-full bg-primary-50 text-primary-700">{icon}</span><strong className="text-ui-data">{label}</strong><span className="ml-auto max-w-[58%] truncate text-right text-xs text-ink-600">{value}</span>{expanded ? <CaretUp aria-hidden="true" className="shrink-0 text-ink-400" size="var(--icon-xs)" /> : <CaretDown aria-hidden="true" className="shrink-0 text-ink-400" size="var(--icon-xs)" />}</button><div className={`grid transition-[grid-template-rows,opacity] duration-200 ease-out motion-reduce:transition-none ${expanded ? "grid-rows-[1fr] opacity-100" : "grid-rows-[0fr] opacity-0"}`}><div className="overflow-hidden"><div className="mb-3 rounded-xl bg-surface-muted px-4 py-3 text-ui-data leading-5">{detail}</div></div></div></div>;
}
